#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Static analysis... "
echo "*********************************************************"

./gradlew spotlessApply

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Static analysis found violations it could not fix."
    echo "Run ./gradlew ktlintFormat to fix formatting related issues..."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi

echo "*********************************************************"
echo "Running git pre-commit hook. Running test cases... "
echo "*********************************************************"

./gradlew test connectedAndroidTest

# Check if tests failed
if [ $? -ne 0 ]; then
  echo "Error: Tests failed. Please fix before committing."
  exit 1
fi